name: output-from-a-job chapter7

on:
  # push:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    # need to define a new outputs section for that job with the output value pulled from the step
    outputs:
      build-stage: ${{ steps.set-debug-stage.outputs.BUILD_STAGE }}

    steps:
      - name: Set debug
        id: set-debug-stage
        run: echo "BUILD_STAGE=debug" >> $GITHUB_OUTPUT

  report:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get stage
        # It is cleaner to reference build-stage via an environment variable in a job
        env:
          # To get the value from the first job, the step in the second job uses the needs.<job>.outputs.<output value name> syntax.
          BUILD_STAGE: ${{ needs.setup.outputs.build-stage }}
        run: echo "The build stage is $BUILD_STAGE"
