# Workflow to demo installing a package and executing on a self-hosted runner
name: file tree chapter5
 
on:
  workflow_dispatch:
jobs:
    
  file-tree:

    runs-on: self-hosted
    steps:
    - name: Install tree
      run: |
        arch -arm64 brew update
        arch -arm64 brew install tree
    - name: Execute tree
      run: time tree | tee filetreelist.txt
