name: system-environment-settings chapter6

on:
  push:

# More on defaults variable settings: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaults
defaults:
  run:
    shell: sh
    working-directory: ./workdir

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./test
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "in test, when defaults are specified at both level, the job settings will override the workflow settings."
          echo "shell=$shell"
          echo "working-directory=${working-directory}"
  report-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
  report-url_too:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  report-os:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check-os
        if: runner.os != 'Windows'
        run: echo "The runner's operating system is $RUNNER_OS."